# Pandas
### Data manaipulation in tables

### work with tables(rows and columns)

In [226]:
import os
import pandas as pd
import numpy as np

In [227]:
df = pd.read_csv(r"/home/user/Desktop/Training/Pandas/project/Bike/Used_Bikes.csv")

In [228]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [229]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [230]:
df.head(15)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
10,Yamaha YZF-R15 2.0 150cc,72000.0,Bangalore,20000.0,First Owner,7.0,150.0,Yamaha
11,Yamaha FZ25 250cc,95000.0,Bangalore,9665.0,First Owner,4.0,250.0,Yamaha
12,Bajaj Pulsar NS200,78000.0,Bangalore,9900.0,First Owner,4.0,200.0,Bajaj
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj

In [231]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [232]:
df.age

0         3.0
1         4.0
2         8.0
3         4.0
4         3.0
         ...
32643     4.0
32644     9.0
32645     6.0
32646    16.0
32647    13.0
Name: age, Length: 32648, dtype: float64

In [233]:
df['age']

0         3.0
1         4.0
2         8.0
3         4.0
4         3.0
         ...
32643     4.0
32644     9.0
32645     6.0
32646    16.0
32647    13.0
Name: age, Length: 32648, dtype: float64

In [234]:
df[['age']]

        age
0       3.0
1       4.0
2       8.0
3       4.0
4       3.0
...     ...
32643   4.0
32644   9.0
32645   6.0
32646  16.0
32647  13.0

[32648 rows x 1 columns]

In [235]:
df[['city']]

            city
0      Ahmedabad
1          Delhi
2          Delhi
3      Bangalore
4      Bangalore
...          ...
32643      Delhi
32644     Karnal
32645      Delhi
32646     Jaipur
32647       Pune

[32648 rows x 1 columns]

In [236]:
df['brand'].nunique()

23

In [237]:
df['owner'].nunique()

4

In [238]:
df['brand'].nunique()

23

In [239]:
df['owner'].value_counts()

owner
First Owner             29964
Second Owner             2564
Third Owner               108
Fourth Owner Or More       12
Name: count, dtype: int64

In [240]:
df.duplicated().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool>

In [241]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [242]:
df.duplicated().sum()

np.int64(25324)

In [243]:
df.drop_duplicates(inplace=True)

In [244]:
df.duplicated().sum()

np.int64(0)

In [245]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [246]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [247]:
# df.dropna(inplace=True)

In [248]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [249]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [250]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [251]:
an = df.select_dtypes(include='object')
an

/tmp/ipykernel_7547/4178628475.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  an = df.select_dtypes(include='object')

            owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [252]:
num=df.select_dtypes(exclude='object')
num

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [253]:
df.to_csv('ankush.csv')

In [254]:
an['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [255]:
owner_dict = {
    'First Owner':1, 
    'Second Owner':2, 
    'Third Owner':3, 
    'Fourth Owner Or More':4
              }

an['owner']=an['owner'].map(owner_dict)

In [256]:
an

      owner            brand
0         1              TVS
1         1    Royal Enfield
2         1          Triumph
3         1              TVS
4         1           Yamaha
...     ...              ...
9362      1             Hero
9369      1            Bajaj
9370      1  Harley-Davidson
9371      1            Bajaj
9372      1            Bajaj

[7324 rows x 2 columns]

In [257]:
an['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [258]:
owner_dict = {
     'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
          'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
          'Yezdi':21,              'MV':22,           'Ideal':23
  
              }

an['brand']=an['brand'].map(owner_dict)

In [259]:
an

      owner  brand
0         1      1
1         1      2
2         1      3
3         1      1
4         1      4
...     ...    ...
9362      1      6
9369      1      7
9370      1     15
9371      1      7
9372      1      7

[7324 rows x 2 columns]

In [260]:
total_df = pd.concat([an,num],axis=1)

In [261]:
total_df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
9362      1      6   25000.0     48587.0  8.0  150.0
9369      1      7   35000.0     60000.0  9.0  220.0
9370      1     15  450000.0      3430.0  4.0  750.0
9371      1      7  139000.0     21300.0  4.0  400.0
9372      1      7   80000.0      7127.0  5.0  220.0

[7324 rows x 6 columns]

In [262]:
total_df.duplicated().sum()

np.int64(18)

In [263]:
total_df.drop_duplicates(inplace=True)

In [264]:
total_df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
9362      1      6   25000.0     48587.0  8.0  150.0
9369      1      7   35000.0     60000.0  9.0  220.0
9370      1     15  450000.0      3430.0  4.0  750.0
9371      1      7  139000.0     21300.0  4.0  400.0
9372      1      7   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [265]:
total_df.isnull().sum()

owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [266]:
x = total_df.drop('brand',axis=1)

In [267]:
x

      owner     price  kms_driven  age  power
0         1   35000.0     17654.0  3.0  110.0
1         1  119900.0     11000.0  4.0  350.0
2         1  600000.0       110.0  8.0  675.0
3         1   65000.0     16329.0  4.0  180.0
4         1   80000.0     10000.0  3.0  150.0
...     ...       ...         ...  ...    ...
9362      1   25000.0     48587.0  8.0  150.0
9369      1   35000.0     60000.0  9.0  220.0
9370      1  450000.0      3430.0  4.0  750.0
9371      1  139000.0     21300.0  4.0  400.0
9372      1   80000.0      7127.0  5.0  220.0

[7306 rows x 5 columns]

In [268]:
y =total_df[['brand']]
y

      brand
0         1
1         2
2         3
3         1
4         4
...     ...
9362      6
9369      7
9370     15
9371      7
9372      7

[7306 rows x 1 columns]

In [269]:
df.to_csv('ankush2.csv')

### filterning

In [270]:
import pandas as pd
import numpy as np
import os
df = pd.read_csv('Used_Bikes.csv')
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [271]:
tvs_df = df[df['brand']=='TVS']

In [272]:
tvs_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [273]:
tvs_first_owner_df = tvs_df[tvs_df['owner']=='First Owner']
tvs_first_owner_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [274]:
tvs_first_owner_df[tvs_first_owner_df['kms_driven']>=50000]

,bike_name,price,city,kms_driven,owner,age,power,brand
437,TVS Apache 150cc,10200.0,Delhi,71474.0,First Owner,12.0,150.0,TVS
1007,TVS Star City Plus 110cc,22918.0,Howrah,79685.0,First Owner,5.0,110.0,TVS
1224,TVS Apache RTR 180cc,28000.0,Ghaziabad,50000.0,First Owner,7.0,180.0,TVS
1334,TVS Suzuki Shogun 110cc,100000.0,Bangalore,66000.0,First Owner,23.0,110.0,TVS
1363,TVS Suzuki Shogun 110cc,100000.0,Bangalore,66000.0,First Owner,23.0,110.0,TVS
1816,TVS Apache RTR 160cc,47000.0,Delhi,55326.0,First Owner,5.0,160.0,TVS
2204,TVS Apache RTR 160cc,30000.0,Bangalore,54500.0,First Owner,9.0,160.0,TVS
2302,TVS Apache RTR 160cc,19542.0,Jaipur,56592.0,First Owner,9.0,160.0,TVS
2395,TVS Apache RTR 160cc,19542.0,Jaipur,56592.0,First Owner,9.0,160.0,TVS
2762,TVS Apache RTR 180cc,35000.0,Noida,67363.0,First Owner,8.0,180.0,TVS
3121,TVS Star City 110cc,9000.0,Delhi,72302.0,First Owner,15.0,110.0,TVS
3174,TVS Apache RTR 160cc,26000.0,Ghaziabad,51875.0,First Owner,9.0,160.0,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000.0,Bangalore,52198.0,First Owner,2.0,160.0,TVS
3196,TVS Apache RTR 160cc,26000.0,Ghaziabad,51875.0,First Owner,9.0,160.0,TVS
3576,TVS Apache RTR 180cc,48000.0,Delhi,64831.0,First Owner,5.0,180.0,TVS
4150,TVS Apache RTR 160cc,20000.0,Gurgaon,52487.0,First Owner,12.0,160.0,TVS
4465,TVS Apache RTR 160cc,20000.0,Gurgaon,52487.0,First Owner,12.0,160.0,TVS
4517,TVS Apache RTR 160cc,18500.0,Faridabad,96142.0,First Owner,10.0,160.0,TVS
4778,TVS Apache RTR 180cc,22000.0,Salem,65000.0,First Owner,9.0,180.0,TVS
4854,TVS Star Sport 100cc,11000.0,Gurgaon,52000.0,First Owner,14.0,100.0,TVS
4856,TVS Apache 150cc,23000.0,Bangalore,174638.0,First Owner,14.0,150.0,TVS
4984,TVS Star Sport 100cc,11000.0,Gurgaon,52000.0,First Owner,14.0,100.0,TVS
4986,TVS Apache 150cc,23000.0,Bangalore,174638.0,First Owner,14.0,150.0,TVS
5163,TVS Star 100cc,9000.0,Ghaziabad,72378.0,First Owner,15.0,100.0,TVS
5282,TVS Apache RTR 160cc,40000.0,Chennai,80000.0,First Owner,9.0,160.0,TVS
5584,TVS Apache RTR 200 4V FI,62000.0,Darbhanga,76663.0,First Owner,4.0,200.0,TVS
5742,TVS Apache RTR 160cc,40000.0,Chennai,80000.0,First Owner,9.0,160.0,TVS
5789,TVS Victor GX 110cc,18000.0,Mumbai,68857.0,First Owner,15.0,110.0,TVS
6072,TVS Star City Plus 110cc,28000.0,Gurgaon,99813.0,First Owner,5.0,110.0,TVS
6551,TVS Star City Plus 110cc,28000.0,Gurgaon,99813.0,First Owner,5.0,110.0,TVS
6840,TVS Apache RTR 200 4V ABS Race Edition,100000.0,Chennai,87735.0,First Owner,3.0,200.0,TVS
7147,TVS Apache RTR 160cc,25700.0,Pune,50000.0,First Owner,10.0,160.0,TVS
7175,TVS Apache RTR 160cc,15000.0,Gurgaon,85086.0,First Owner,14.0,160.0,TVS
7311,TVS Apache RTR 180cc,70000.0,Jaipur,207102.0,First Owner,2.0,180.0,TVS
7660,TVS Sport 100cc,12200.0,Ghaziabad,58000.0,First Owner,10.0,100.0,TVS
8135,TVS Apache RTR 180cc,34000.0,Sirsa,53817.0,First Owner,9.0,180.0,TVS
8208,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,90000.0,Ahmedabad,52594.0,First Owner,3.0,200.0,TVS
8476,TVS Apache RTR 180cc,26000.0,Delhi,61041.0,First Owner,10.0,180.0,TVS
8842,TVS Apache RTR 180cc ABS,45000.0,Jabalpur,50000.0,First Owner,7.0,180.0,TVS
8997,TVS Apache RTR 160cc,24000.0,Jabalpur,266028.0,First Owner,10.0,160.0,TVS
9076,TVS Star City 110cc,16000.0,Chennai,53520.0,First Owner,9.0,110.0,TVS
9084,TVS Star City 110cc,18000.0,Chennai,92466.0,First Owner,9.0,110.0,TVS
9112,TVS Star City 110cc,16000.0,Chennai,53520.0,First Owner,9.0,110.0,TVS
9120,TVS Star City 110cc,18000.0,Chennai,92466.0,First Owner,9.0,110.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS

new condication

In [275]:
RoyalEnfield_df = df[df['brand']=='Royal Enfield']
RoyalEnfield_df

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32601,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,First Owner,4.0,350.0,Royal Enfield
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

In [276]:
RoyalEnfield_first_owner_df=RoyalEnfield_df[RoyalEnfield_df['owner']=='First Owner']

In [277]:
RoyalEnfield_first_owner_df

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32595,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32601,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,First Owner,4.0,350.0,Royal Enfield
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

In [278]:
age = RoyalEnfield_first_owner_df[RoyalEnfield_first_owner_df['kms_driven']>=50]
RoyalEnfield_first_owner_df

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32595,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32601,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,First Owner,4.0,350.0,Royal Enfield
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

In [279]:
price=age[age['age']>=1]
age

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32595,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32601,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,First Owner,4.0,350.0,Royal Enfield
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

In [280]:
price[price['price']==200000]

,bike_name,price,city,kms_driven,owner,age,power,brand
1458,Royal Enfield Thunderbird X 500cc,200000.0,Coimbatore,6300.0,First Owner,3.0,500.0,Royal Enfield
3190,Royal Enfield Classic Desert Storm 500cc,200000.0,Bangalore,10000.0,First Owner,4.0,500.0,Royal Enfield
3251,Royal Enfield Himalayan 410cc Sleet Edition,200000.0,Bangalore,8094.0,First Owner,3.0,410.0,Royal Enfield

In [281]:
royal_data = df[(df['brand']=='Royal Enfield')&
                (df['owner']=='First Owner')&
(df['kms_driven']<=50000)&
(df['age']<=2)&
(df['price']<=200000)]

royal_data

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7422,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
7559,Royal Enfield Bullet 500cc,170000.0,Delhi,8015.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [282]:
# df.query("brand=='RoyalEnfield'and")

In [284]:
hero_data = df[(df['brand']=='Hero')&
                (df['owner']=='second Owner')&
(df["kms_driven"]<=350)&
(df['age']<=2)&
(df["price"]<=700000/2)]

hero_data

Empty DataFrame
Columns: [bike_name, price, city, kms_driven, owner, age, power, brand]
Index: []