In [152]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [153]:
df = pd.read_csv(r'/home/user/Desktop/Training/Project/Bike/Data/clen_bike.csv')
df

      Unnamed: 0  owner            brand     price  kms_driven  age  power
0              0      1              TVS   35000.0     17654.0  3.0  110.0
1              1      1    Royal Enfield  119900.0     11000.0  4.0  350.0
2              2      1          Triumph  600000.0       110.0  8.0  675.0
3              3      1              TVS   65000.0     16329.0  4.0  180.0
4              4      1           Yamaha   80000.0     10000.0  3.0  150.0
...          ...    ...              ...       ...         ...  ...    ...
7301        9362      1             Hero   25000.0     48587.0  8.0  150.0
7302        9369      1            Bajaj   35000.0     60000.0  9.0  220.0
7303        9370      1  Harley-Davidson  450000.0      3430.0  4.0  750.0
7304        9371      1            Bajaj  139000.0     21300.0  4.0  400.0
7305        9372      1            Bajaj   80000.0      7127.0  5.0  220.0

[7306 rows x 7 columns]

In [154]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.drop

<bound method DataFrame.drop of       owner            brand     price  kms_driven  age  power
0         1              TVS   35000.0     17654.0  3.0  110.0
1         1    Royal Enfield  119900.0     11000.0  4.0  350.0
2         1          Triumph  600000.0       110.0  8.0  675.0
3         1              TVS   65000.0     16329.0  4.0  180.0
4         1           Yamaha   80000.0     10000.0  3.0  150.0
...     ...              ...       ...         ...  ...    ...
7301      1             Hero   25000.0     48587.0  8.0  150.0
7302      1            Bajaj   35000.0     60000.0  9.0  220.0
7303      1  Harley-Davidson  450000.0      3430.0  4.0  750.0
7304      1            Bajaj  139000.0     21300.0  4.0  400.0
7305      1            Bajaj   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]>

In [155]:
df.duplicated().sum()

np.int64(0)

In [156]:
df.isnull().sum()

owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [157]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [158]:
brand_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
              }

df['brand']=df['brand'].map(brand_dict)

In [159]:
df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7301      1      6   25000.0     48587.0  8.0  150.0
7302      1      7   35000.0     60000.0  9.0  220.0
7303      1     15  450000.0      3430.0  4.0  750.0
7304      1      7  139000.0     21300.0  4.0  400.0
7305      1      7   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [160]:
x = df.drop(['price'],axis=1)

In [161]:
y = df[['price']]

In [162]:
x

      owner  brand  kms_driven  age  power
0         1      1     17654.0  3.0  110.0
1         1      2     11000.0  4.0  350.0
2         1      3       110.0  8.0  675.0
3         1      1     16329.0  4.0  180.0
4         1      4     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
7301      1      6     48587.0  8.0  150.0
7302      1      7     60000.0  9.0  220.0
7303      1     15      3430.0  4.0  750.0
7304      1      7     21300.0  4.0  400.0
7305      1      7      7127.0  5.0  220.0

[7306 rows x 5 columns]

In [163]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7301   25000.0
7302   35000.0
7303  450000.0
7304  139000.0
7305   80000.0

[7306 rows x 1 columns]

In [164]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [165]:
x_test

      owner  brand  kms_driven   age  power
7062      1      5     35000.0   9.0  250.0
4553      1     14      9066.0   5.0  250.0
6505      1      6     48000.0  17.0  100.0
1918      1      7     20222.0   5.0  150.0
5227      1      8     27167.0   5.0  150.0
...     ...    ...         ...   ...    ...
2045      1      5     98971.0   8.0  150.0
527       1     14      2881.0   7.0  250.0
1783      1      2      6517.0   2.0  350.0
5065      1      2      5222.0   5.0  350.0
565       1      1      2980.0   6.0  160.0

[1462 rows x 5 columns]

In [166]:
x_train

      owner  brand  kms_driven  age  power
6302      1      1     12061.0  4.0  180.0
7037      2      7     40000.0  7.0  220.0
640       1      6     28329.0  6.0  110.0
6153      2      7     10000.0  8.0  220.0
1755      1      5     26000.0  8.0  150.0
...     ...    ...         ...  ...    ...
5191      1      7     15383.0  2.0  100.0
5226      1      8     45263.0  6.0  150.0
5390      1      6     45000.0  6.0  100.0
860       1      4     14836.0  8.0  150.0
7270      1      4      2126.0  3.0  250.0

[5844 rows x 5 columns]

In [167]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

In [168]:
y_train

         price
6302   65000.0
7037   49000.0
640    32000.0
6153   36000.0
1755   70000.0
...        ...
5191   38000.0
5226   62000.0
5390   30000.0
860    40000.0
7270  115800.0

[5844 rows x 1 columns]

In [169]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5844, 5), (1462, 5), (5844, 1), (1462, 1))

In [170]:
print(x_test.isnull().sum())
print(x_train.isnull().sum())

owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64
owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64

In [171]:
x.isnull().sum()

owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64

# # SVM (SVR)

In [172]:
x.isnull().sum()

owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64

In [173]:
from sklearn.svm import SVC,SVR
sv=SVR()
sv.fit(x_train,y_train)
pred = sv.predict(x_train)
pred

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([54818.29669472, 53851.92403358, 54223.38009998, ...,
       53753.63779878, 54731.65323559, 55017.26498108], shape=(5844,))

In [174]:
pred=sv.predict(x_test)
pred

array([53990.22593309, 54898.09273564, 53714.93508548, ...,
       54953.11680016, 54976.1473673 , 55007.82068255], shape=(1462,))

In [175]:

print('SVR test score:-',sv.score(x_test,y_test))
print('SVR train score:-',sv.score(x_train,y_train))

SVR test score:- -0.05789256698689371
SVR train score:- -0.06164747200042009

# # SVM (SVC)

In [176]:
from sklearn.datasets import load_breast_cancer,load_diabetes
x,y=load_breast_cancer(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)
print('test score:-',sv.score(x_test,y_test))
print('train score:-',sv.score(x_train,y_train))

test score:- 0.9473684210526315
train score:- 0.9142857142857143

# # Linear Regression

In [177]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [178]:
pred=lr.predict(x_test)
pred

array([ 0.62168355,  0.17803853,  0.27512068,  1.1320503 ,  1.11698318,
       -0.66303713, -0.07355607,  0.44212355,  0.28085763,  0.96360261,
        0.794142  ,  0.33192584,  0.90481757,  0.39666504,  0.9336697 ,
        0.17750175,  0.91013271,  1.19445658,  1.41615414,  0.04464718,
        0.65041677,  0.8752756 , -0.38792384,  1.08061015,  0.96215276,
        0.84678947,  0.99807141,  0.87049439,  0.94386257, -0.16893149,
        1.0238613 ,  1.04190872,  0.81604445,  0.9156589 ,  1.07186427,
        0.84289045,  0.48746626,  0.62375262,  0.25368547,  0.76842229,
        1.15259719,  0.03799193,  0.97126513,  0.99773732,  0.55160057,
        0.65587474,  0.91828081,  1.02580964,  0.80527854,  1.01543748,
        0.20974453, -0.07875586,  0.55842968,  0.59037896,  1.02323689,
        0.78572959,  0.93959678, -0.36416183,  0.55847881,  1.04937824,
        0.94406266, -0.1953921 , -0.35465216,  0.80776979,  0.90208492,
        0.58309865, -0.16982229, -0.15422403,  0.97877451,  0.83434684,
        0.09123074,  0.09531931,  0.8486583 ,  0.25871356,  0.9949576 ,
        0.83561759,  0.80204781,  0.58575204,  1.17901275,  0.75766173,
        0.40996133,  1.05654014,  0.53031006, -0.13159216,  0.3191878 ,
        0.14061625, -0.36596822,  0.03857742,  0.98036084,  0.94278356,
        0.82407548,  0.79194847,  0.80018521,  1.10421683,  0.98984354,
        0.9565251 , -0.00308431, -0.19926989,  1.03364721,  0.13044771,
        0.24557297,  1.27709941,  0.21094783,  0.15733386,  0.76399441,
        0.74121238,  0.80363351, -0.10971523,  0.708626  ,  0.74741164,
        0.16156221,  0.96791348,  0.56621261,  0.13303589])

In [179]:
print('test score:-',lr.score(x_test,y_test))
print('train score:-',lr.score(x_train,y_train))

test score:- 0.727101612622356
train score:- 0.7789778474553671

In [180]:
from sklearn.linear_model import LogisticRegression
log =LogisticRegression()
log.fit(x_train,y_train)
print("LogisticRegression training",log.score(x_train,y_train))
print("LogisticRegression testing",log.score(x_test,y_test))

LogisticRegression training 0.9560439560439561
LogisticRegression testing 0.956140350877193

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# # DecisionTreeClassifier

In [181]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.datasets import load_iris
x, y =load_iris(return_X_y=True)
x_train, x_test, y_train, y_test= train_test_split(x, y,test_size=0.2, random_state=42)
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [182]:

print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

test score:- 1.0
train score:- 1.0

# with perameter

In [183]:
dt.get_params()

# %%
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.datasets import load_iris
x, y =load_iris(return_X_y=True)
x_train, x_test, y_train, y_test= train_test_split(x, y,test_size=0.2, random_state=42)
dt =DecisionTreeClassifier(criterion='entropy', min_samples_split=3, min_samples_leaf=2, random_state=42)
dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=3, random_state=42)

In [184]:

print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

test score:- 1.0
train score:- 0.975

#  DecisionTreeRegressor

In [188]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.datasets import load_iris
x, y =load_iris(return_X_y=True)
x_train, x_test, y_train, y_test= train_test_split(x, y,test_size=0.2, random_state=42)
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [189]:
print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

test score:- 1.0
train score:- 1.0

# with perameter

In [186]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.datasets import load_iris
# from sklearn.model_selection import train_test_split
# x, y = load_iris(return_X_y=True)
# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# dt = DecisionTreeRegressor(criterion='squared_error',min_samples_split=3,min_samples_leaf=2,random_state=42)
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [187]:
print("Test Score:", dt.score(x_test, y_test))
print("Train Score:", dt.score(x_train, y_train))

Test Score: 1.0
Train Score: 1.0

In [190]:
import joblib
joblib.dump(sv,"sv_load.lp")

['sv_load.lp']

In [191]:
model = joblib.load('/home/user/Desktop/Training/Project/Bike/Model/sv_load.lp')

In [192]:
model

SVC()