In [150]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [151]:
df = pd.read_csv(r'clean_data.csv')
df

      Unnamed: 0  owner  brand     price  kms_driven  age  power
0              0      1    NaN   35000.0     17654.0  3.0  110.0
1              1      1    NaN  119900.0     11000.0  4.0  350.0
2              2      1    NaN  600000.0       110.0  8.0  675.0
3              3      1    NaN   65000.0     16329.0  4.0  180.0
4              4      1    NaN   80000.0     10000.0  3.0  150.0
...          ...    ...    ...       ...         ...  ...    ...
7301        7301      1    NaN   25000.0     48587.0  8.0  150.0
7302        7302      1    NaN   35000.0     60000.0  9.0  220.0
7303        7303      1    NaN  450000.0      3430.0  4.0  750.0
7304        7304      1    NaN  139000.0     21300.0  4.0  400.0
7305        7305      1    NaN   80000.0      7127.0  5.0  220.0

[7306 rows x 7 columns]

In [152]:
df['brand'] = df['brand'].fillna(df['brand'].mean())

In [177]:
df

      owner  brand     price  kms_driven  age  power
0         1    NaN   35000.0     17654.0  3.0  110.0
1         1    NaN  119900.0     11000.0  4.0  350.0
2         1    NaN  600000.0       110.0  8.0  675.0
3         1    NaN   65000.0     16329.0  4.0  180.0
4         1    NaN   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7301      1    NaN   25000.0     48587.0  8.0  150.0
7302      1    NaN   35000.0     60000.0  9.0  220.0
7303      1    NaN  450000.0      3430.0  4.0  750.0
7304      1    NaN  139000.0     21300.0  4.0  400.0
7305      1    NaN   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [153]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.drop

<bound method DataFrame.drop of       owner  brand     price  kms_driven  age  power
0         1    NaN   35000.0     17654.0  3.0  110.0
1         1    NaN  119900.0     11000.0  4.0  350.0
2         1    NaN  600000.0       110.0  8.0  675.0
3         1    NaN   65000.0     16329.0  4.0  180.0
4         1    NaN   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7301      1    NaN   25000.0     48587.0  8.0  150.0
7302      1    NaN   35000.0     60000.0  9.0  220.0
7303      1    NaN  450000.0      3430.0  4.0  750.0
7304      1    NaN  139000.0     21300.0  4.0  400.0
7305      1    NaN   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]>

In [154]:
df.duplicated().sum()

np.int64(11)

In [155]:
df.isnull().sum()

owner            0
brand         7306
price            0
kms_driven       0
age              0
power            0
dtype: int64

In [156]:
df['brand'].unique()

array([nan])

In [157]:
brand_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
              }

df['brand']=df['brand'].map(brand_dict)

In [158]:
df.to_csv("clean_data.csv")

In [159]:
x = df.drop(['price'],axis=1)

In [160]:
y = df[['price']]

In [161]:
x

      owner  brand  kms_driven  age  power
0         1    NaN     17654.0  3.0  110.0
1         1    NaN     11000.0  4.0  350.0
2         1    NaN       110.0  8.0  675.0
3         1    NaN     16329.0  4.0  180.0
4         1    NaN     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
7301      1    NaN     48587.0  8.0  150.0
7302      1    NaN     60000.0  9.0  220.0
7303      1    NaN      3430.0  4.0  750.0
7304      1    NaN     21300.0  4.0  400.0
7305      1    NaN      7127.0  5.0  220.0

[7306 rows x 5 columns]

In [162]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7301   25000.0
7302   35000.0
7303  450000.0
7304  139000.0
7305   80000.0

[7306 rows x 1 columns]

In [163]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [164]:
x_test

      owner  brand  kms_driven   age  power
7062      1    NaN     35000.0   9.0  250.0
4553      1    NaN      9066.0   5.0  250.0
6505      1    NaN     48000.0  17.0  100.0
1918      1    NaN     20222.0   5.0  150.0
5227      1    NaN     27167.0   5.0  150.0
...     ...    ...         ...   ...    ...
2045      1    NaN     98971.0   8.0  150.0
527       1    NaN      2881.0   7.0  250.0
1783      1    NaN      6517.0   2.0  350.0
5065      1    NaN      5222.0   5.0  350.0
565       1    NaN      2980.0   6.0  160.0

[1462 rows x 5 columns]

In [165]:
x_train

      owner  brand  kms_driven  age  power
6302      1    NaN     12061.0  4.0  180.0
7037      2    NaN     40000.0  7.0  220.0
640       1    NaN     28329.0  6.0  110.0
6153      2    NaN     10000.0  8.0  220.0
1755      1    NaN     26000.0  8.0  150.0
...     ...    ...         ...  ...    ...
5191      1    NaN     15383.0  2.0  100.0
5226      1    NaN     45263.0  6.0  150.0
5390      1    NaN     45000.0  6.0  100.0
860       1    NaN     14836.0  8.0  150.0
7270      1    NaN      2126.0  3.0  250.0

[5844 rows x 5 columns]

In [166]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

In [167]:
y_train

         price
6302   65000.0
7037   49000.0
640    32000.0
6153   36000.0
1755   70000.0
...        ...
5191   38000.0
5226   62000.0
5390   30000.0
860    40000.0
7270  115800.0

[5844 rows x 1 columns]

In [168]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5844, 5), (1462, 5), (5844, 1), (1462, 1))

In [169]:
print(x_test.isnull().sum())
print(x_train.isnull().sum())

owner            0
brand         1462
kms_driven       0
age              0
power            0
dtype: int64
owner            0
brand         5844
kms_driven       0
age              0
power            0
dtype: int64

In [170]:
x.isnull().sum()

owner            0
brand         7306
kms_driven       0
age              0
power            0
dtype: int64

# # SVM (SVR)

In [171]:
x.isnull().sum()

owner            0
brand         7306
kms_driven       0
age              0
power            0
dtype: int64

In [172]:
x_train.isnull().sum()

owner            0
brand         5844
kms_driven       0
age              0
power            0
dtype: int64

In [173]:
print(x_train.isnull().sum())
print(x_train.dtypes)

owner            0
brand         5844
kms_driven       0
age              0
power            0
dtype: int64
owner           int64
brand         float64
kms_driven    float64
age           float64
power         float64
dtype: object

In [174]:
x_train['brand'] = x_train['brand'].fillna(x_train['brand'].mean())
x_test['brand'] = x_test['brand'].fillna(x_train['brand'].mean())

In [175]:
x_train.isnull().sum()

owner            0
brand         5844
kms_driven       0
age              0
power            0
dtype: int64

In [176]:
from sklearn.svm import SVC,SVR
sv=SVR()
sv.fit(x_train,y_train)
pred = sv.predict(x_train)
pred

ValueError: Input X contains NaN.
SVR does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
pred=sv.predict(x_test)
pred

In [ ]:

print('SVR test score:-',sv.score(x_test,y_test))
print('SVR train score:-',sv.score(x_train,y_train))

# # SVM (SVC)

In [ ]:
from sklearn.datasets import load_breast_cancer,load_diabetes
x,y=load_breast_cancer(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)
print('test score:-',sv.score(x_test,y_test))
print('train score:-',sv.score(x_train,y_train))

# # Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

In [ ]:
pred=lr.predict(x_test)
pred

In [ ]:
print('test score:-',lr.score(x_test,y_test))
print('train score:-',lr.score(x_train,y_train))

In [ ]:
from sklearn.linear_model import LogisticRegression
log =LogisticRegression()
log.fit(x_train,y_train)
print("LogisticRegression training",log.score(x_train,y_train))
print("LogisticRegression testing",log.score(x_test,y_test))

# # DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.datasets import load_iris
x, y =load_iris(return_X_y=True)
x_train, x_test, y_train, y_test= train_test_split(x, y,test_size=0.2, random_state=42)
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)

In [ ]:

print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

# with perameter

In [ ]:
dt.get_params()

# %%
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.datasets import load_iris
x, y =load_iris(return_X_y=True)
x_train, x_test, y_train, y_test= train_test_split(x, y,test_size=0.2, random_state=42)
dt =DecisionTreeClassifier(criterion='entropy', min_samples_split=3, min_samples_leaf=2, random_state=42)
dt.fit(x_train, y_train)

In [ ]:

print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

#  DecisionTreeRegressor

In [ ]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

from sklearn.datasets import load_iris
x, y =load_iris(return_X_y=True)
x_train, x_test, y_train, y_test= train_test_split(x, y,test_size=0.2, random_state=42)
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

In [ ]:
print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

# with perameter

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.datasets import load_iris
# from sklearn.model_selection import train_test_split
# x, y = load_iris(return_X_y=True)
# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# dt = DecisionTreeRegressor(criterion='squared_error',min_samples_split=3,min_samples_leaf=2,random_state=42)
dt.fit(x_train, y_train)

In [ ]:
print("Test Score:", dt.score(x_test, y_test))
print("Train Score:", dt.score(x_train, y_train))

In [ ]:
import joblib
joblib.dump(sv,"bike_load.lp")

In [ ]:
# model = joblib.load(')