In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(r'clen_bike.csv')
df

      Unnamed: 0  owner            brand     price  kms_driven  age  power
0              0      1              TVS   35000.0     17654.0  3.0  110.0
1              1      1    Royal Enfield  119900.0     11000.0  4.0  350.0
2              2      1          Triumph  600000.0       110.0  8.0  675.0
3              3      1              TVS   65000.0     16329.0  4.0  180.0
4              4      1           Yamaha   80000.0     10000.0  3.0  150.0
...          ...    ...              ...       ...         ...  ...    ...
7301        9362      1             Hero   25000.0     48587.0  8.0  150.0
7302        9369      1            Bajaj   35000.0     60000.0  9.0  220.0
7303        9370      1  Harley-Davidson  450000.0      3430.0  4.0  750.0
7304        9371      1            Bajaj  139000.0     21300.0  4.0  400.0
7305        9372      1            Bajaj   80000.0      7127.0  5.0  220.0

[7306 rows x 7 columns]

In [3]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isnull().sum()

owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [6]:
df.drop_duplicates().sum()

owner                                                      8092
brand         TVSRoyal EnfieldTriumphTVSYamahaYamahaHondaHer...
price                                               619579084.0
kms_driven                                          174826977.0
age                                                     48654.0
power                                                 1665629.0
dtype: object

In [7]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [8]:
brand_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
              }

df['brand']=df['brand'].map(brand_dict)

In [9]:
df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7301      1      6   25000.0     48587.0  8.0  150.0
7302      1      7   35000.0     60000.0  9.0  220.0
7303      1     15  450000.0      3430.0  4.0  750.0
7304      1      7  139000.0     21300.0  4.0  400.0
7305      1      7   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [10]:
df.to_csv("clean_data.csv")

In [11]:
x = df.drop(['price'],axis=1)

In [12]:
y = df[['price']]

In [13]:
x

      owner  brand  kms_driven  age  power
0         1      1     17654.0  3.0  110.0
1         1      2     11000.0  4.0  350.0
2         1      3       110.0  8.0  675.0
3         1      1     16329.0  4.0  180.0
4         1      4     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
7301      1      6     48587.0  8.0  150.0
7302      1      7     60000.0  9.0  220.0
7303      1     15      3430.0  4.0  750.0
7304      1      7     21300.0  4.0  400.0
7305      1      7      7127.0  5.0  220.0

[7306 rows x 5 columns]

In [14]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7301   25000.0
7302   35000.0
7303  450000.0
7304  139000.0
7305   80000.0

[7306 rows x 1 columns]

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [16]:
x_test

      owner  brand  kms_driven   age  power
7062      1      5     35000.0   9.0  250.0
4553      1     14      9066.0   5.0  250.0
6505      1      6     48000.0  17.0  100.0
1918      1      7     20222.0   5.0  150.0
5227      1      8     27167.0   5.0  150.0
...     ...    ...         ...   ...    ...
2045      1      5     98971.0   8.0  150.0
527       1     14      2881.0   7.0  250.0
1783      1      2      6517.0   2.0  350.0
5065      1      2      5222.0   5.0  350.0
565       1      1      2980.0   6.0  160.0

[1462 rows x 5 columns]

In [17]:
x_train

      owner  brand  kms_driven  age  power
6302      1      1     12061.0  4.0  180.0
7037      2      7     40000.0  7.0  220.0
640       1      6     28329.0  6.0  110.0
6153      2      7     10000.0  8.0  220.0
1755      1      5     26000.0  8.0  150.0
...     ...    ...         ...  ...    ...
5191      1      7     15383.0  2.0  100.0
5226      1      8     45263.0  6.0  150.0
5390      1      6     45000.0  6.0  100.0
860       1      4     14836.0  8.0  150.0
7270      1      4      2126.0  3.0  250.0

[5844 rows x 5 columns]

In [18]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

In [19]:
y_train

         price
6302   65000.0
7037   49000.0
640    32000.0
6153   36000.0
1755   70000.0
...        ...
5191   38000.0
5226   62000.0
5390   30000.0
860    40000.0
7270  115800.0

[5844 rows x 1 columns]

In [20]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5844, 5), (1462, 5), (5844, 1), (1462, 1))

In [21]:
print(x_test.isnull().sum())
print(x_train.isnull().sum())

owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64
owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64

In [22]:
x.isnull().sum()

owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64

# # SVM (SVR)

In [23]:
from sklearn.svm import SVC,SVR
sv=SVR()
sv.fit(x_train,y_train)

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [24]:
pred=sv.predict(x_test)
pred

array([53990.22593309, 54898.09273564, 53714.93508548, ...,
       54953.11680016, 54976.1473673 , 55007.82068255], shape=(1462,))

In [25]:

print('SVR test score:-',sv.score(x_test,y_test))
print('SVR train score:-',sv.score(x_train,y_train))

SVR test score:- -0.05789256698689371
SVR train score:- -0.06164747200042009

# # SVM (SVC)

In [26]:
from sklearn.svm import SVC
sv = SVC()
sv.fit(x_train,y_train)

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [27]:
pred=sv.predict(x_test)
print(pred)


print('SVC test score:-',sv.score(x_test,y_test))
print('SVC train score:-',sv.score(x_train,y_train))

[35000. 65000. 25000. ... 90000. 90000. 90000.]
SVC test score:- 0.0280437756497948
SVC train score:- 0.03199863107460643

# # Linear Regression

In [28]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [29]:
pred=lr.predict(x_test)
pred

array([[ 83929.37665135],
       [180558.39832151],
       [-22099.35939509],
       ...,
       [141514.63936524],
       [131317.3298484 ],
       [ 10099.13186721]], shape=(1462, 1))

In [30]:
print('test score:-',lr.score(x_test,y_test))
print('train score:-',lr.score(x_train,y_train))

test score:- 0.7434808272417729
train score:- 0.7116425245703818

# logisticRegression

In [31]:
from sklearn.linear_model import LogisticRegression
log =LogisticRegression()
log.fit(x_train,y_train)

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [32]:
print("LogisticRegression training",log.score(x_train,y_train))
print("LogisticRegression testing",log.score(x_test,y_test))

LogisticRegression training 0.024640657084188913
LogisticRegression testing 0.0280437756497948

# # DecisionTreeClassifier

In [33]:
from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [34]:

print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

test score:- 0.03898768809849521
train score:- 0.9493497604380561

# with perameter

In [35]:
dt.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [36]:
from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier(criterion='entropy', min_samples_split=3, min_samples_leaf=2, random_state=42)
dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=3, random_state=42)

In [37]:
pred=dt.predict(x_test)
print(pred)
print('DecisionTreeClassifier test score:-',dt.score(x_test,y_test))
print('DecisionTreeClassifier train score:-',dt.score(x_train,y_train))

[100000. 190000.  15000. ... 129500.  90000.  65000.]
DecisionTreeClassifier test score:- 0.032147742818057455
DecisionTreeClassifier train score:- 0.4710814510609172

#  DecisionTreeRegressor

In [38]:
from sklearn.tree import DecisionTreeRegressor
import joblib
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [39]:
print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

test score:- 0.8452501581410413
train score:- 0.9978073030729452

In [40]:
joblib.dump(dt, 'DecisionTreeRegressor_model.lb')
print("Model saved successfully!")

Model saved successfully!

In [41]:
model=joblib.load('DecisionTreeRegressor_model.lb')
print(model.predict(x_test))

[ 85000. 155000.  10669. ... 170000. 110000.  63000.]

# with perameter

In [42]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(criterion='squared_error',min_samples_split=3,min_samples_leaf=2,random_state=42)
dt.fit(x_train, y_train)

DecisionTreeRegressor(min_samples_leaf=2, min_samples_split=3, random_state=42)

In [43]:
print("Test Score:", dt.score(x_test, y_test))
print("Train Score:", dt.score(x_train, y_train))

Test Score: 0.8450540574036833
Train Score: 0.9743177859999623