In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns

In [96]:
df = pd.read_csv(r"/home/user/Desktop/Training/Project/Loan/Data/loan_approval.csv")
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [97]:
df.head()
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [98]:
df.shape

(2000, 8)

In [99]:
df.columns

Index(['name', 'city', 'income', 'credit_score', 'loan_amount',
       'years_employed', 'points', 'loan_approved'],
      dtype='str')

In [100]:
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2000 non-null   str
 1   city            2000 non-null   str
 2   income          2000 non-null   int64
 3   credit_score    2000 non-null   int64
 4   loan_amount     2000 non-null   int64
 5   years_employed  2000 non-null   int64
 6   points          2000 non-null   float64
 7   loan_approved   2000 non-null   bool
dtypes: bool(1), float64(1), int64(4), str(2)
memory usage: 111.5 KB

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [101]:
print(df.isnull().sum())

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [102]:
df.duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool>

In [103]:
df.drop_duplicates()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [104]:
df.duplicated().sum()

np.int64(0)

In [105]:
df.drop_duplicates(inplace=True)

In [106]:
df.drop_duplicates().sum()

name              Allison HillBrandon HallRhonda SmithGabrielle ...
city              East JillNew JamessideLake RobertoWest Melanie...
income                                                    181171954
credit_score                                                1147892
loan_amount                                                50617006
years_employed                                                40882
points                                                     113360.0
loan_approved                                                   879
dtype: object

In [107]:
df.duplicated().sum()

np.int64(0)

In [108]:
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [109]:
df.isnull().sum()
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [110]:
print(df.describe())

              income  credit_score   loan_amount  years_employed       points
count    2000.000000   2000.000000   2000.000000     2000.000000  2000.000000
mean    90585.977000    573.946000  25308.503000       20.441000    56.680000
std     34487.874907    160.564945  14207.320147       11.777813    18.638033
min     30053.000000    300.000000   1022.000000        0.000000    10.000000
25%     61296.250000    433.000000  12748.750000       10.000000    45.000000
50%     90387.500000    576.000000  25661.500000       21.000000    55.000000
75%    120099.750000    715.000000  37380.500000       31.000000    70.000000
max    149964.000000    850.000000  49999.000000       40.000000   100.000000

In [111]:
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [112]:
for col in df.columns:
    print("\nColumn:", col)
    print(df[col].unique())

Column: name
<StringArray>
[        'Allison Hill',         'Brandon Hall',         'Rhonda Smith',
      'Gabrielle Davis',         'Valerie Gray',       'Darren Roberts',
           'Holly Wood',      'Nicholas Martin',          'Patty Perez',
           'Emily Rios',
 ...
       'Rebecca Newman', 'Christopher Morrison',        'Sierra Gentry',
        'Hannah Carter',          'Ryan Thomas',       'James Schaefer',
            'Diana Lin',        'Brandon Meyer',          'Jason Price',
         'Nicole Brown']
Length: 2000, dtype: str

Column: city
<StringArray>
[       'East Jill',    'New Jamesside',     'Lake Roberto',
 'West Melanieview',        'Mariastad',  'Port Jesseville',
      'Lake Joseph',       'Nelsonside',  'Port Leslieview',
   'Wilkersonmouth',
 ...
    'South Kenneth',        'Cookshire',     'Jenniferstad',
          'Basston',        'Tylertown',        'Robertton',
        'New Frank',       'East Haley',         'Adamland',
   'New Nathantown']
Length: 1882, dtype: str

Column: income
[113810  44592  33278 ...  41957 139022  41188]

Column: credit_score
[389 729 584 344 496 689 373 524 367 446 670 365 573 819 843 380 469 682
 525 543 716 400 443 792 592 362 382 383 434 402 748 406 651 345 309 451
 405 481 658 659 482 418 638 712 608 518 395 374 775 624 760 750 456 698
 385 634 353 471 326 548 370 574 688 310 802 784 613 795 669 789 611 761
 512 781 570 572 630 341 393 807 713 810 424 416 725 724 692 315 646 336
 667 691 461 609 322 535 340 479 793 706 690 364 333 321 521 433 787 375
 601 533 683 361 594 356 307 746 596 390 526 454 772 773 813 553 641 617
 458 685 720 616 814 579 657 401 780 840 768 739 838 436 486 342 756 581
 457 621 420 597 505 432 346 708 399 620 520 410 499 431 821 827 726 332
 632 800 654 440 391 337 605 816 314 715 554 311 618 414 752 435 560 783
 759 421 774 493 334 522 542 452 447 508 640 825 727 645 473 349 766 306
 483 384 516 466 742 305 824 598 606 633 484 686 849 709 387 468 714 491
 697 604 444 477 796 850 523 749 511 599 360 801 751 612 531 372 386 510
 806 730 568 823 359 422 575 378 347 767 805 832 376 702 411 762 331 312
 351 662 721 652 587 546 660 413 665 700 808 804 744 696 723 541 506 848
 786 492 462 817 785 320 404 565 527 485 650 304 495 836 675 407 569 731
 794 529 758 300 649 763 408 423 426 743 580 593 355 501 666 628 846 639
 717 602 798 636 674 392 830 829 790 464 301 538 835 465 833 704 656 769
 664 343 586 308 673 576 480 556 398 381 590 745 615 847 699 803 428 619
 701 503 582 680 497 409 562 536 684 316 379 532 453 350 502 740 324 539
 318 354 455 507 330 488 494 438 631 352 668 366 737 776 607 329 357 812
 514 626 736 779 764 430 710 513 678 540 437 478 842 643 559 563 741 637
 544 782 472 429 722 530 797 537 755 595 459 450 625 734 837 815 419 489
 841 754 811 600 661 327 644 778 834 733 545 818 534 728 707 771 388 610
 475 732 831 302 753 319 561 403 588 705 845 325 449 358 445 550 629 377
 648 647 371 552 655 555 711 549 338 693 677 558 718 583 442 439 747 427
 566 687 571 504 313 770 603 694 809 519 323 839 498 844 695 777 417 474
 585 642 577 515 547 412 397 339 396 676 735 394 567 703 441 681 470 826
 828 500 589 335 328 622 820 490 799 679 765 551 368 627 467 369 463 791
 415 303 591 528 564 317 460 557 348 653 822 788 635 623 757]

Column: loan_amount
[39698 15446 11189 ... 16752 24031 31397]

Column: years_employed
[27 28 13 29  4 40 20 36  8 24 21 38 31 33  6 25 11 34 35  3 37 19 16  1
 14 32 18 30 26  0 39 15 12  2 22  7  9 23 17 10  5]

Column: points
[ 50.  55.  45.  25.  65.  35.  20.  75. 100.  80.  60.  30.  10.  70.
  90.  40.  85.  95.  15.]

Column: loan_approved
[False  True]

In [113]:
df = df.drop(['name', 'city'], axis=1)

In [114]:
print(df.columns)

Index(['income', 'credit_score', 'loan_amount', 'years_employed', 'points',
       'loan_approved'],
      dtype='str')

In [115]:
corr_matrix = df.corr(numeric_only=True)

print(corr_matrix)

                  income  credit_score  loan_amount  years_employed    points  \
income          1.000000     -0.027113     0.037612       -0.014441  0.451142
credit_score   -0.027113      1.000000    -0.008076        0.023598  0.740899
loan_amount     0.037612     -0.008076     1.000000        0.013015 -0.223039
years_employed -0.014441      0.023598     0.013015        1.000000  0.156441
points          0.451142      0.740899    -0.223039        0.156441  1.000000
loan_approved   0.238066      0.715788    -0.157859        0.104408  0.821415

                loan_approved
income               0.238066
credit_score         0.715788
loan_amount         -0.157859
years_employed       0.104408
points               0.821415
loan_approved        1.000000

In [116]:
df.to_csv(
    "loan_approval_cleaned.csv",
    index=False
)

In [117]:
df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [118]:
df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [119]:
x = df.drop(['loan_amount'],axis=1)
x

      income  credit_score  years_employed  points  loan_approved
0     113810           389              27    50.0          False
1      44592           729              28    55.0          False
2      33278           584              13    45.0          False
3     127196           344              29    50.0          False
4      66048           496               4    25.0          False
...      ...           ...             ...     ...            ...
1995   92163           770              13    85.0           True
1996   38799           635              17    40.0          False
1997   41957           763               5    60.0           True
1998  139022           360              35    55.0          False
1999   41188           482               6    20.0          False

[2000 rows x 5 columns]

In [120]:
y = df[['loan_amount']]
y

      loan_amount
0           39698
1           15446
2           11189
3           48823
4           47174
...           ...
1995        12251
1996        48259
1997        16752
1998        24031
1999        31397

[2000 rows x 1 columns]

In [121]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [122]:
x_train,x_test,y_train,y_test =train_test_split(x,y,train_size=0.2,random_state=43)

In [123]:
x_train

      income  credit_score  years_employed  points  loan_approved
1572   43173           442              25    30.0          False
1962   42999           751              32    60.0           True
101   121988           400               6    45.0          False
1987   70966           305              23    35.0          False
1791   94569           736               9    75.0           True
...      ...           ...             ...     ...            ...
277    78944           774              37    75.0           True
1841  138028           818              28    95.0           True
255    46483           384              27    25.0          False
1344  106720           823              10    95.0           True
1860  130290           447              10    55.0          False

[400 rows x 5 columns]

In [124]:
y_train

      loan_amount
1572        14488
1962        32075
101         42533
1987        38462
1791         7439
...           ...
277         45535
1841        28231
255         33758
1344        13650
1860        16496

[400 rows x 1 columns]

In [125]:
x_test

      income  credit_score  years_employed  points  loan_approved
1480  129991           704               5    75.0           True
1312  108385           548              24    60.0           True
305    97391           531              28    45.0          False
1545  142635           684               1    60.0           True
1716   95771           792              11    85.0           True
...      ...           ...             ...     ...            ...
1177  121411           442              29    50.0          False
1221  111057           683              18    75.0           True
1637   80422           760               8    70.0           True
488   115717           656              17    70.0           True
510   124058           833              26    95.0           True

[1600 rows x 5 columns]

In [126]:
y_test

      loan_amount
1480        14246
1312         7279
305         35042
1545        37053
1716        13675
...           ...
1177        31664
1221        31846
1637        39694
488         23772
510         30510

[1600 rows x 1 columns]

In [127]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((400, 5), (1600, 5), (400, 1), (1600, 1))

In [128]:
df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [129]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [130]:
pred =lr.predict(x_test)
pred

array([[26649.18318787],
       [28097.56443685],
       [35704.11698811],
       ...,
       [23817.42954775],
       [27163.25704233],
       [21950.42731279]], shape=(1600, 1))

In [131]:
y_test

      loan_amount
1480        14246
1312         7279
305         35042
1545        37053
1716        13675
...           ...
1177        31664
1221        31846
1637        39694
488         23772
510         30510

[1600 rows x 1 columns]

In [132]:
print('test score: = ',lr.score(x_test,y_test))
print('train score: = ',lr.score(x_train,y_train))

test score: =  0.2505421839080739
train score: =  0.3098306776236408

In [133]:
from sklearn.svm import SVC,SVR
sv = SVR()
sv.fit(x_train,y_train)

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [134]:
print('test score:--',sv.score(x_test,y_test))
print('train score:--',sv.score(x_train,y_train))

test score:-- 1.6832747310790985e-05
train score:-- 1.8494629355436665e-05

In [135]:
from sklearn.datasets import load_breast_cancer,load_diabetes
import joblib
x,y = load_breast_cancer(return_X_y=True)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.svm import SVC
sv =SVC()
sv.fit(x_train,y_train)
print('test score:--',sv.score(x_test,y_test))
print('train score:--',sv.score(x_train,y_train))
joblib.dump(sv,"sv_load.lb")

test score:-- 0.9473684210526315
train score:-- 0.9142857142857143

['sv_load.lb']

LogisticRegression

In [136]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
x,y = load_breast_cancer(return_X_y=True)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
log.fit(x_train,y_train)

/home/user/Desktop/Training/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [137]:
print('test score:--',log.score(x_test,y_test))
print('train score:--',log.score(x_train,y_train))

test score:-- 0.956140350877193
train score:-- 0.9560439560439561

peramitors

In [138]:
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
# from sklearn.datasets import load_iris
# x,y = load_iris(return_X_y=True)
# x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
dt= DecisionTreeClassifier(criterion='entropy',min_samples_split=3,min_samples_leaf=2,random_state=42)
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=3, random_state=42)

In [139]:
print('test score:--',dt.score(x_test,y_test))
print('train score:--',dt.score(x_train,y_train))

test score:-- 0.956140350877193
train score:-- 0.9934065934065934