In [64]:
! pip3 install scikit-learn

Requirement already satisfied: scikit-learn in /home/user/Desktop/Training/.venv/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /home/user/Desktop/Training/.venv/lib/python3.12/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in /home/user/Desktop/Training/.venv/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /home/user/Desktop/Training/.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /home/user/Desktop/Training/.venv/lib/python3.12/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/user/Desktop/Training/.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

In [65]:
import os
import pandas as pd
import numpy as np
import seaborn as sks
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('clen_bike.csv')
df

      Unnamed: 0  owner            brand     price  kms_driven  age  power
0              0      1              TVS   35000.0     17654.0  3.0  110.0
1              1      1    Royal Enfield  119900.0     11000.0  4.0  350.0
2              2      1          Triumph  600000.0       110.0  8.0  675.0
3              3      1              TVS   65000.0     16329.0  4.0  180.0
4              4      1           Yamaha   80000.0     10000.0  3.0  150.0
...          ...    ...              ...       ...         ...  ...    ...
7301        9362      1             Hero   25000.0     48587.0  8.0  150.0
7302        9369      1            Bajaj   35000.0     60000.0  9.0  220.0
7303        9370      1  Harley-Davidson  450000.0      3430.0  4.0  750.0
7304        9371      1            Bajaj  139000.0     21300.0  4.0  400.0
7305        9372      1            Bajaj   80000.0      7127.0  5.0  220.0

[7306 rows x 7 columns]

In [ ]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.drop

In [68]:
df.duplicated().sum()

np.int64(0)

In [69]:
df.isnull().sum()

owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [70]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [71]:
owner_dict = {
     'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
          'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
          'Yezdi':21,              'MV':22,           'Ideal':23
  
              }

df['brand']=df['brand'].map(owner_dict)

In [72]:
df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7301      1      6   25000.0     48587.0  8.0  150.0
7302      1      7   35000.0     60000.0  9.0  220.0
7303      1     15  450000.0      3430.0  4.0  750.0
7304      1      7  139000.0     21300.0  4.0  400.0
7305      1      7   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [73]:
x= df.drop(['price'],axis=1)
x

      owner  brand  kms_driven  age  power
0         1      1     17654.0  3.0  110.0
1         1      2     11000.0  4.0  350.0
2         1      3       110.0  8.0  675.0
3         1      1     16329.0  4.0  180.0
4         1      4     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
7301      1      6     48587.0  8.0  150.0
7302      1      7     60000.0  9.0  220.0
7303      1     15      3430.0  4.0  750.0
7304      1      7     21300.0  4.0  400.0
7305      1      7      7127.0  5.0  220.0

[7306 rows x 5 columns]

In [74]:
y = df[['price']]
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7301   25000.0
7302   35000.0
7303  450000.0
7304  139000.0
7305   80000.0

[7306 rows x 1 columns]

In [75]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.2,random_state=43)

In [76]:
x_test

      owner  brand  kms_driven   age  power
2332      1      1     12917.0   3.0  160.0
1415      1      4     24000.0   4.0  150.0
4642      1     10     19960.0   7.0  200.0
2153      1      6     70756.0  13.0  100.0
2461      1      2      2000.0   4.0  350.0
...     ...    ...         ...   ...    ...
6265      1      1      4524.0   3.0  160.0
1279      1     15      9000.0   6.0  750.0
2884      1      4     56113.0  11.0  150.0
5727      1      7     21890.0   8.0  200.0
5718      1      5     14244.0   5.0  150.0

[5845 rows x 5 columns]

In [77]:
x_train

      owner  brand  kms_driven   age  power
5613      1      2     34000.0   6.0  500.0
6900      1      7     16000.0  11.0  180.0
795       2      7     49000.0   7.0  200.0
1970      1      5     16000.0   8.0  125.0
6220      1      2     20764.0   4.0  350.0
...     ...    ...         ...   ...    ...
6202      1      7     17169.0   4.0  400.0
2325      1     14     10500.0   6.0  250.0
2303      1      2     11600.0   7.0  350.0
3392      1      2     47518.0  11.0  500.0
5956      1      5     17000.0   7.0  150.0

[1461 rows x 5 columns]

In [78]:
y_test

         price
2332   65000.0
1415   55000.0
4642   75000.0
2153   14000.0
2461   90000.0
...        ...
6265   82000.0
1279  428600.0
2884   16500.0
5727   53500.0
5718   33000.0

[5845 rows x 1 columns]

In [79]:
y_test

         price
2332   65000.0
1415   55000.0
4642   75000.0
2153   14000.0
2461   90000.0
...        ...
6265   82000.0
1279  428600.0
2884   16500.0
5727   53500.0
5718   33000.0

[5845 rows x 1 columns]

In [80]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1461, 5), (5845, 5), (1461, 1), (5845, 1))

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [82]:
pred =lr.predict(x_test)
pred

array([[ 14730.67255455],
       [ 30831.97033565],
       [108706.33454628],
       ...,
       [  6546.25913784],
       [ 78747.87001819],
       [ 38953.99545648]], shape=(5845, 1))

In [83]:
y_test

         price
2332   65000.0
1415   55000.0
4642   75000.0
2153   14000.0
2461   90000.0
...        ...
6265   82000.0
1279  428600.0
2884   16500.0
5727   53500.0
5718   33000.0

[5845 rows x 1 columns]

In [84]:
print('test score: = ',lr.score(x_test,y_test))
print('train score: = ',lr.score(x_train,y_train))

test score: =  0.7144660783720993
train score: =  0.7302500163332111